config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category


end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories


end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: {minimum: 3, maximum: 25},
                          uniqueness: {case_sensitive: false}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
                                    length: { maximum: 105},
                                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id])  if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]



  def show
  end

  def index
      @articles  = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
     if @article.save
       flash[:notice] = "Article was created successfully"
       redirect_to article_path(@article)
     else
       render 'new'
    end
  end

  def update

       if @article.update(article_params)
         flash[:notice] = "Article was successfully edited"
         redirect_to @article
      else
        render 'edit'
      end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Your new category has been created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles  = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "Category name successfully updated"
        redirect_to @category
      else
        render "edit"
      end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully logged in"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect login details"
      render 'new'
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def  new
    @user = User.new
  end

  def index
    @users  = User.all
  end

  def show
    @articles  = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}. You registered to Alpha Blog"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:username,:email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You may only edit or delete your own account"
       redirect_to @user
     end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def gravatar_for(user, options = {size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "shadow rounded d-block mx-auto")
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
 <div class="row justify-content-md-center">
   <div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-header font-italic">
    <% if article.user%>
      by <%= link_to article.user.username, user_path(article.user) %>
      <% end %>
      <% if article.categories.any? %>
        <div class="mt-2"><%= render article.categories %></div>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
      <p class="card-text"><%= truncate(article.description, length: 100) %></p>
      <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>

      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
      <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
      <% end %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(article.created_at) %> ago,
    Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
    </div>
  </div>
  </div>
 </div>
<% end %>

</div>

app/views/articles/_form.html.erb
<div class="container">


<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true, class: "shadow p-3 mb-3 light-green rounded")   do |f| %>

  <div class="form-group row">
    <%= f.label :title, class: "col-2 col-form-label text-white" %>
   <div class="col-10">
    <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
  </div>
 </div>

 <div class="form-group row">
   <%= f.label :description, class: "col-2 col-form-label text-white" %>
  <div class="col-10">
   <%= f.text_area :description,rows: 10,  class: "form-control shadow rounded",
    placeholder: "Description of article" %>
 </div>
</div>

<div class="form-group row">
   <%= f.label :category, class: "col-2 col-form-label text-white" %>
  <div class="col-10">
  <%= f.collection_select(:category_ids, Category.all, :id, :name,
  {prompt: "Make your selection from the list below (can be empty)"},
  {multiple: true, size: 3, class: "custom-select form-control shadow rounded"}) %>
 </div>
</div>

<div class="form-group row  justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>

<% end %>
</div>
<div class="mb-3">
<%= link_to '[ Cancel and return to articles listing ]', articles_path %>
</div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Recent Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create A New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">

 <div class="row justify-content-md-center">
   <div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-header font-italic">
      by <%= @article.user.username if @article.user %>
      <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
      <% if @article.categories.any? %>
        <div class="mt-2"><%= render @article.categories %></div>
      <% end %>
    </div>
    <div class="card-body">
      <div class="card-text text-left"><%= simple_format(@article.description) %></div>
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
      <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
      <% end %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
    Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
    </div>
  </div>
  </div>
 </div>


</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info text-white" %>

app/views/categories/_form.html.erb
 <%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 light-green rounded")   do |f| %>

  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-white" %>
   <div class="col-10">
    <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
  </div>
 </div>

<div class="form-group row  justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category info</h1>

<div class="container">


<div class="row justify-content-center">
  <div class="col-10">
   <%= render 'form' %>
</div>
<div class="mb-3">
<%= link_to '[ Cancel and return to category  ]', category_path(@category) %>
</div>
</div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Post Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
<% @categories.each do |category| %>
 <div class="row justify-content-md-center">
   <div class="col-4 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
      <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>

      </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(category.created_at) %> ago,
    Edited <%= time_ago_in_words(category.updated_at) %> ago</small>
    </div>
  </div>
  </div>
 </div>
<% end %>
</div>


<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category for posts</h1>

<div class="container">


<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 light-green rounded")   do |f| %>

  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-white" %>
   <div class="col-10">
    <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
  </div>
 </div>

<div class="form-group row  justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>

<% end %>
</div>
<div class="mb-3">
<%= link_to '[ Cancel and return to articles listing ]', articles_path %>
</div>
</div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category),class: "btn btn-outline-info" %>
    </div>
  <% end %>


<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
   <div class="container text-center">
     <small>Copyright &copy; <%= link_to "Andrew Grablewski", "https://github.com/andrewgrablewski", class:"text-white" %></small>
   </div>
 </footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>

    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dissmissable fade show" role="alert" >
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <li class="nav-item active">
      <%= link_to "Bloggers", users_path, class: "nav-link" %>
  </li>
  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Articles
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if logged_in?  %>
      <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
      <% end %>
      <%= link_to "View articles", articles_path, class: "dropdown-item" %>

    </div>
  </li>
  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Categories
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if logged_in? && current_user.admin?  %>
      <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
      <% end %>
      <%= link_to "View categories", categories_path, class: "dropdown-item" %>
      </div>
  </li>
  <% if logged_in? %>
  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     Profile <%= "(Admin)" if current_user.admin? %> [<%= current_user.username %>]
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

      <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Delete your profile", user_path(current_user),
               class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      <div class="dropdown-divider"></div>
      <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete  %>
    </div>
  </li>
    </ul>
    <% end %>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
              <% if logged_in? %>

                    <li class="nav-item active">
                        <%= link_to "Logout", logout_path, class: "nav-link",  method: :delete %>
                    </li>

                <% else %>
                    <li class="nav-item active">
                        <%= link_to "Login", login_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to "Sign up", signup_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page</h1>

<%= link_to 'List of Articles', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<p></p>
<div  class="container">
  <div class="jumbotron">
  <!--<h1 class="display-4 mt-4 text-gray mb-1">Alpha Blog</h1> -->
  <div id="typekeys" class="mt-20 mb-10"></div>
  <p class="lead ">Blog application from  Mashrur Hossain's<br /> Complete
  Rails Developer Udemy course</p>
  <hr class="my-3">
  <p id="trailer">Coded with Rails 6, Ruby and Bootstrap.</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-large"%>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %>
     from being saved:</h4>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">


<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, local: true, class: "shadow p-3 mb-3 light-green rounded")   do |f| %>

  <div class="form-group row">
    <%= f.label :username, class: "col-2 col-form-label text-white" %>
   <div class="col-10">
    <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
  </div>
 </div>

 <div class="form-group row">
   <%= f.label :email, class: "col-2 col-form-label text-white" %>
  <div class="col-10">
   <%= f.email_field :email, class: "form-control shadow rounded",
    placeholder: "Enter your email address" %>
 </div>
</div>

<div class="form-group row">
  <%= f.label :password, class: "col-2 col-form-label text-white" %>
 <div class="col-10">
  <%= f.password_field :password, class: "form-control shadow rounded",
   placeholder: "Choose a password" %>
</div>
</div>



<div class="form-group row  justify-content-center">
  <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
</div>

<% end %>
</div>
<div class="mb-3">
<%= link_to '[ Cancel and return to articles listing ]', articles_path %>
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
<% @users.each do |user| %>
 <div class="row justify-content-md-center">
   <div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-header font-italic">
       <%= link_to user.username, user %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
      <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>


      <%= link_to "View profile", user, class: "btn btn-outline-success" %>
      <% if logged_in? %>
        <% if user == current_user %>
      <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to "Delete profile", user_path(user), class: "btn btn-outline-danger",
           method: :delete, data: {confirm: "Are you sure you want to delete the user and all associated articles?"} %> 
          <% end %>
      <% end %>


  </div>
  <div class="card-footer text-muted">
    <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
    </div>
  </div>
  </div>
 </div>
<% end %>
</div>
<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 200 %>



  <% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user),class: "btn btn-outline-info" %>
    </div>
  <% end %>


<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>